php:
  build: .
  ports:
      - 80:80
  restart: always
  links:
      - mysql

mysql:
    image: mysql:5.7.22
    restart: always
    ports:
      - "3306:3306"
    volumes:
        - ./db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
